#!/bin/sh -e
bogus=''' '
if [ ! -e .bootstrap ]; then
    virtualenv .bootstrap
    .bootstrap/bin/pip install jinja2
fi
.bootstrap/bin/python $0 $*
exit
'''

import re
from itertools import product, chain
from jinja2 import FileSystemLoader
from jinja2 import Environment
jinja = Environment(loader=FileSystemLoader('.'), trim_blocks=True, lstrip_blocks=True)

pythons = ['2.7', '2.6', '3.3', '3.4', 'pypy']
deps = [
    'Django>=1.3,<1.4',
    'Django>=1.4,<1.5',
    'Django>=1.5,<1.6',
    'Django>=1.6,<1.7',
    'https://www.djangoproject.com/download/1.7b3/tarball/',
]
covers = [True, False]
envs = ['']
skips = list(chain(
    # skip 1.3 and 1.4 on py3
    product(['3.3', '3.4'], [dep for dep in deps if '1.4' in dep], covers, envs),
    # skip 1.7 on py2.6
    product(['2.6'], [dep for dep in deps if '1.7' in dep], covers, envs),
))
tox = {}
for python, dep, cover, env in product(pythons, deps, covers, envs):
    if (python, dep, cover, env) not in skips:
        tox['-'.join(filter(None, (
            python,
            '-'.join(re.sub(r'[A-Za-z/:.>]+[/=](.*?)(,.*|/.*)?$', r'\1', dep).split(' ')),
            '' if cover else 'nocover',
            env and env.lower().replace('_', '').rstrip('=yes'),
        )))] = {
            'python': 'python' + python if 'py' not in python else python,
            'deps': dep.split(),
            'cover': cover,
            'env': env,
        }

open('tox.ini', 'w').write(jinja.get_template('tox.tmpl.ini').render(envs=tox))
open('.travis.yml', 'w').write(jinja.get_template('.travis.tmpl.yml').render(envs=tox))
